#!/bin/bash
set -e
set -u

POSTGRES="psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER"

echo "Creating database & role: $NEXTCLOUD_DB_USER"
$POSTGRES <<-EOSQL
CREATE USER $NEXTCLOUD_DB_USER WITH PASSWORD '$NEXTCLOUD_DB_PASSWORD';
CREATE DATABASE $NEXTCLOUD_DB OWNER $NEXTCLOUD_DB_USER;
EOSQL

echo "Creating database & role: $GRAFANA_DB_USER"
$POSTGRES <<-EOSQL
CREATE USER $GRAFANA_DB_USER WITH CREATEDB PASSWORD '$GRAFANA_DB_PASSWORD';
CREATE DATABASE $GRAFANA_DB OWNER $GRAFANA_DB_USER;
EOSQL

